# Generated by Django 5.0.6 on 2024-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('page_sub', models.TextField()),
                ('page_desc', models.TextField()),
                ('bannerimg', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
