# Generated by Django 5.0.6 on 2024-08-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0005_appealhandling_appealhandlingmeta_appealhandlingpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainHandlingMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.TextField()),
                ('robots', models.TextField()),
                ('googlebot', models.TextField()),
                ('language', models.TextField()),
                ('google_site_verification', models.TextField()),
                ('og_url', models.TextField()),
                ('og_type', models.TextField()),
                ('og_title', models.TextField()),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='og_images/')),
                ('twitter_card', models.TextField()),
                ('twitter_domain', models.TextField()),
                ('twitter_url', models.TextField()),
                ('twitter_title', models.TextField()),
                ('twitter_desc', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='twitter_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ComplainHandlingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
                ('bgimg', models.ImageField(upload_to='complain_handling_page_bg/')),
                ('diagram', models.ImageField(upload_to='complain_handling_page_diagram/')),
            ],
        ),
        migrations.CreateModel(
            name='CHList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('complain_handling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch_list', to='subone.complainhandlingpage')),
            ],
        ),
    ]
