# Generated by Django 5.0.6 on 2024-08-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0007_grievancesmeta_grievancespage_grievanceslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.TextField()),
                ('robots', models.TextField()),
                ('googlebot', models.TextField()),
                ('language', models.TextField()),
                ('google_site_verification', models.TextField()),
                ('og_url', models.TextField()),
                ('og_type', models.TextField()),
                ('og_title', models.TextField()),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='og_images/')),
                ('twitter_card', models.TextField()),
                ('twitter_domain', models.TextField()),
                ('twitter_url', models.TextField()),
                ('twitter_title', models.TextField()),
                ('twitter_desc', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='twitter_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationProcessPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
                ('BGimg', models.ImageField(upload_to='bg_images/')),
                ('diagram', models.ImageField(upload_to='diagrams/')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsForIssuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpandingOrReducing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrantOrRefuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintainCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestoringOfCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionOfCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawOfCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('sub_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DFIList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('details_for_issuing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfi_list', to='subone.detailsforissuing')),
            ],
        ),
        migrations.CreateModel(
            name='EORList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('expanding_or_reducing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eor_list', to='subone.expandingorreducing')),
            ],
        ),
        migrations.CreateModel(
            name='GOrRList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('grant_or_refuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gor_list', to='subone.grantorrefuse')),
            ],
        ),
        migrations.CreateModel(
            name='MCList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('maintain_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mc_list', to='subone.maintaincertification')),
            ],
        ),
        migrations.CreateModel(
            name='ROCList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('restoring_of_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roc_list', to='subone.restoringofcertification')),
            ],
        ),
        migrations.CreateModel(
            name='SOCList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('suspension_of_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soc_list', to='subone.suspensionofcertification')),
            ],
        ),
        migrations.CreateModel(
            name='WOCList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('withdraw_of_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woc_list', to='subone.withdrawofcertification')),
            ],
        ),
    ]
