# Generated by Django 5.0.6 on 2024-08-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0010_aboutcontent_approachstep_certification_client1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerificationProcessImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_title', models.TextField()),
                ('mainImg', models.ImageField(upload_to='bg_images/')),
            ],
        ),
    ]
