# Generated by Django 5.0.6 on 2024-08-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0011_cerificationprocessimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrcMetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('googlebot', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('google_site_verification', models.CharField(max_length=255)),
                ('og_url', models.CharField(max_length=255)),
                ('og_type', models.CharField(max_length=50)),
                ('og_title', models.CharField(max_length=255)),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='images/')),
                ('twitter_card', models.CharField(max_length=50)),
                ('twitter_domain', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('twitter_title', models.CharField(max_length=255)),
                ('twitter_description', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SecEightGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SecFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SecFourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecOneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecSevenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecSixCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SecSixList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecThreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecTwoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('grid', models.ManyToManyField(related_name='sec_eight_grid', to='subone.seceightgrid')),
            ],
        ),
        migrations.CreateModel(
            name='SecFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('list', models.ManyToManyField(related_name='sec_four_list', to='subone.secfourlist')),
            ],
        ),
        migrations.CreateModel(
            name='SecOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('paragraph_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('list', models.ManyToManyField(related_name='sec_one_list', to='subone.seconelist')),
            ],
        ),
        migrations.CreateModel(
            name='SecSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('list', models.ManyToManyField(related_name='sec_seven_list', to='subone.secsevenlist')),
            ],
        ),
        migrations.CreateModel(
            name='SecSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('category', models.ManyToManyField(related_name='sec_six_category', to='subone.secsixcategory')),
            ],
        ),
        migrations.AddField(
            model_name='secsixcategory',
            name='list',
            field=models.ManyToManyField(related_name='sec_six_list', to='subone.secsixlist'),
        ),
        migrations.CreateModel(
            name='SecThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('list', models.ManyToManyField(related_name='sec_three_list', to='subone.secthreelist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lp_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('url_string', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('GrcMetaTags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_meta_tags', to='subone.grcmetatags')),
                ('sec_eight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_eight', to='subone.seceight')),
                ('sec_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_five', to='subone.secfive')),
                ('sec_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_four', to='subone.secfour')),
                ('sec_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_one', to='subone.secone')),
                ('sec_seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_seven', to='subone.secseven')),
                ('sec_six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_six', to='subone.secsix')),
                ('sec_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_three', to='subone.secthree')),
                ('sec_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_two', to='subone.sectwo')),
            ],
        ),
        migrations.AddField(
            model_name='sectwo',
            name='list',
            field=models.ManyToManyField(related_name='sec_two_list', to='subone.sectwolist'),
        ),
    ]
