# Generated by Django 5.0.6 on 2024-09-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0013_remove_grcsubpage_grcmetatags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrcMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('googlebot', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('google_site_verification', models.CharField(max_length=255)),
                ('og_url', models.CharField(max_length=255)),
                ('og_type', models.CharField(max_length=50)),
                ('og_title', models.CharField(max_length=255)),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='images/')),
                ('twitter_card', models.CharField(max_length=50)),
                ('twitter_domain', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('twitter_title', models.CharField(max_length=255)),
                ('twitter_description', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecEightList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecFourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('imgfield', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecOneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('imgfield', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecSevenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('imgfield', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecSixCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecSixList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('imgfield', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecThreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('imgfield', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecTwoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('imgfield', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('paragraph_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grc_sec_eight_list', models.ManyToManyField(related_name='grc_sec_eight_list', to='subone.grcseceightlist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('grc_sec_four_list', models.ManyToManyField(related_name='grc_sec_four_list', to='subone.grcsecfourlist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('paragraph_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grc_sec_one_list', models.ManyToManyField(related_name='grc_sec_one_list', to='subone.grcseconelist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('grc_sec_seven_list', models.ManyToManyField(related_name='grc_sec_seven_list', to='subone.grcsecsevenlist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('paragraph_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grc_sec_six_category', models.ManyToManyField(related_name='grc_sec_six_category', to='subone.grcsecsixcategory')),
            ],
        ),
        migrations.AddField(
            model_name='grcsecsixcategory',
            name='grc_sec_six_list',
            field=models.ManyToManyField(related_name='grc_sec_six_list', to='subone.grcsecsixlist'),
        ),
        migrations.CreateModel(
            name='GrcSecThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('grc_sec_three_list', models.ManyToManyField(related_name='grc_sec_three_list', to='subone.grcsecthreelist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSecTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('grc_sec_two_list', models.ManyToManyField(related_name='grc_sec_two_list', to='subone.grcsectwolist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcSubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lp_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('url_string', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('grc_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_meta', to='subone.grcmetatag')),
                ('grc_sec_eight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_eight', to='subone.grcseceight')),
                ('grc_sec_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_five', to='subone.grcsecfive')),
                ('grc_sec_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_four', to='subone.grcsecfour')),
                ('grc_sec_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_one', to='subone.grcsecone')),
                ('grc_sec_seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_seven', to='subone.grcsecseven')),
                ('grc_sec_six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_six', to='subone.grcsecsix')),
                ('grc_sec_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_three', to='subone.grcsecthree')),
                ('grc_sec_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_two', to='subone.grcsectwo')),
            ],
        ),
    ]
