# Generated by Django 5.0.6 on 2024-09-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0014_grcmetatag_grcseceightlist_grcsecfive_grcsecfourlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_eight',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_eight', to='subone.grcseceight'),
        ),
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_five',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_five', to='subone.grcsecfive'),
        ),
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_four',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_four', to='subone.grcsecfour'),
        ),
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_one',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_one', to='subone.grcsecone'),
        ),
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_seven',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_seven', to='subone.grcsecseven'),
        ),
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_six',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_six', to='subone.grcsecsix'),
        ),
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_three',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_three', to='subone.grcsecthree'),
        ),
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_sec_two',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_sec_two', to='subone.grcsectwo'),
        ),
    ]
