# Generated by Django 5.0.6 on 2024-09-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0017_trnmetatag_trnsecfivelist_trnsecfourlist_trnsecone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnSecOneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='trnsecone',
            name='trn_sec_one_list',
            field=models.ManyToManyField(related_name='trn_sec_one_list', to='subone.trnseconelist'),
        ),
    ]
