# Generated by Django 5.0.6 on 2024-09-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0018_trnseconelist_trnsecone_trn_sec_one_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrnMetaTag',
            new_name='ManagementTrnMetaTag',
        ),
        migrations.RenameModel(
            old_name='TrnSecFive',
            new_name='ManagementTrnSecFive',
        ),
        migrations.RenameModel(
            old_name='TrnSecFiveList',
            new_name='ManagementTrnSecFiveList',
        ),
        migrations.RenameModel(
            old_name='TrnSecFour',
            new_name='ManagementTrnSecFour',
        ),
        migrations.RenameModel(
            old_name='TrnSecFourList',
            new_name='ManagementTrnSecFourList',
        ),
        migrations.RenameModel(
            old_name='TrnSecOne',
            new_name='ManagementTrnSecOne',
        ),
        migrations.RenameModel(
            old_name='TrnSecThreeList',
            new_name='ManagementTrnSecOneList',
        ),
        migrations.RenameModel(
            old_name='TrnSecSix',
            new_name='ManagementTrnSecSix',
        ),
        migrations.RenameModel(
            old_name='TrnSecSixList',
            new_name='ManagementTrnSecSixList',
        ),
        migrations.RenameModel(
            old_name='TrnSecThree',
            new_name='ManagementTrnSecThree',
        ),
        migrations.RenameModel(
            old_name='TrnSecTwoList',
            new_name='ManagementTrnSecThreeList',
        ),
        migrations.RenameModel(
            old_name='TrnSecTwo',
            new_name='ManagementTrnSecTwo',
        ),
        migrations.RenameModel(
            old_name='TrnSecOneList',
            new_name='ManagementTrnSecTwoList',
        ),
        migrations.RenameModel(
            old_name='TrnSubPage',
            new_name='ManagementTrnSubPage',
        ),
    ]
