# Generated by Django 5.0.6 on 2024-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0019_rename_trnmetatag_managementtrnmetatag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementtrnsecone',
            name='trn_sec_one_list',
            field=models.ManyToManyField(related_name='trn_sec_one_list', to='subone.managementtrnseconelist'),
        ),
        migrations.AlterField(
            model_name='managementtrnsecthree',
            name='trn_sec_three_list',
            field=models.ManyToManyField(related_name='trn_sec_three_list', to='subone.managementtrnsecthreelist'),
        ),
        migrations.AlterField(
            model_name='managementtrnsectwo',
            name='trn_sec_two_list',
            field=models.ManyToManyField(related_name='trn_sec_two_list', to='subone.managementtrnsectwolist'),
        ),
    ]
