# Generated by Django 5.0.6 on 2024-09-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0020_alter_managementtrnsecone_trn_sec_one_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTrnMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('googlebot', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('google_site_verification', models.CharField(max_length=255)),
                ('og_url', models.CharField(max_length=255)),
                ('og_type', models.CharField(max_length=50)),
                ('og_title', models.CharField(max_length=255)),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='images/')),
                ('twitter_card', models.CharField(max_length=50)),
                ('twitter_domain', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('twitter_title', models.CharField(max_length=255)),
                ('twitter_description', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecFiveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecFourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecOneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecSixList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecThreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecTwoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('prf_trn_sec_five_list', models.ManyToManyField(related_name='prf_trn_sec_five_list', to='subone.professionaltrnsecfivelist')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('prf_trn_sec_four_list', models.ManyToManyField(related_name='prf_trn_sec_four_list', to='subone.professionaltrnsecfourlist')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('prf_trn_sec_one_list', models.ManyToManyField(related_name='prf_trn_sec_one_list', to='subone.professionaltrnseconelist')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('prf_trn_sec_six_list', models.ManyToManyField(related_name='prf_trn_sec_six_list', to='subone.professionaltrnsecsixlist')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('prf_trn_sec_three_list', models.ManyToManyField(related_name='prf_trn_sec_three_list', to='subone.professionaltrnsecthreelist')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('prf_trn_sec_two_list', models.ManyToManyField(related_name='prf_trn_sec_two_list', to='subone.professionaltrnsectwolist')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lp_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('url_string', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('prf_trn_meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_meta', to='subone.professionaltrnmetatag')),
                ('prf_trn_sec_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_sec_five', to='subone.professionaltrnsecfive')),
                ('prf_trn_sec_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_sec_four', to='subone.professionaltrnsecfour')),
                ('prf_trn_sec_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_sec_one', to='subone.professionaltrnsecone')),
                ('prf_trn_sec_six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_sec_six', to='subone.professionaltrnsecsix')),
                ('prf_trn_sec_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_sec_three', to='subone.professionaltrnsecthree')),
                ('prf_trn_sec_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_sec_two', to='subone.professionaltrnsectwo')),
            ],
        ),
    ]
