# Generated by Django 5.0.6 on 2024-09-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0021_professionaltrnmetatag_professionaltrnsecfivelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtrnsecone',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementtrnsecone',
            name='sub_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementtrnsecone',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
