# Generated by Django 5.0.6 on 2024-09-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0023_professionaltrnsecone_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTrnSecSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('paragraph_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTrnSecSevenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='managementtrnsecthree',
            name='img',
        ),
        migrations.AddField(
            model_name='managementtrnsectwo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='managementtrnsubpage',
            name='trn_sec_seven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trn_sec_seven', to='subone.managementtrnsecseven'),
        ),
        migrations.AddField(
            model_name='managementtrnsecseven',
            name='trn_sec_seven_list',
            field=models.ManyToManyField(related_name='trn_sec_seven_list', to='subone.managementtrnsecsevenlist'),
        ),
    ]
