# Generated by Django 5.0.6 on 2024-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0025_managementtrnsecfivelist_list_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtrnsecsix',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='managementtrnsecsix',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
