# Generated by Django 5.0.6 on 2024-09-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0026_managementtrnsecsix_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementtrnsecsixlist',
            name='list_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
