# Generated by Django 5.0.6 on 2024-09-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0027_alter_managementtrnsecsixlist_list_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementtrnsecfivelist',
            old_name='list_heading',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='managementtrnsecfive',
            name='trn_sec_five_list',
        ),
        migrations.RemoveField(
            model_name='managementtrnsecfivelist',
            name='list_text',
        ),
        migrations.AddField(
            model_name='managementtrnsecfivelist',
            name='imgfield',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='managementtrnsecfivelist',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ManagementTrnSecFiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('trn_sec_five_list', models.ManyToManyField(related_name='trn_sec_five_list', to='subone.managementtrnsecfivelist')),
            ],
        ),
        migrations.AddField(
            model_name='managementtrnsecfive',
            name='trn_sec_five_category',
            field=models.ManyToManyField(related_name='trn_sec_five_category', to='subone.managementtrnsecfivecategory'),
        ),
    ]
