# Generated by Django 5.0.6 on 2024-09-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0028_rename_list_heading_managementtrnsecfivelist_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTrnSecSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('paragraph_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecSevenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='professionaltrnsecfivelist',
            name='list_text',
        ),
        migrations.RemoveField(
            model_name='professionaltrnsecthree',
            name='img',
        ),
        migrations.AddField(
            model_name='professionaltrnsecfivelist',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaltrnsecfivelist',
            name='imgfield',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='professionaltrnsecfivelist',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaltrnsecsix',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professionaltrnsecsix',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaltrnsectwo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='professionaltrnsecfive',
            name='prf_trn_sec_five_list',
            field=models.ManyToManyField(related_name='prf_trn_sec_five_category', to='subone.professionaltrnsecfivelist'),
        ),
        migrations.CreateModel(
            name='ProfessionalTrnSecFiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('prf_trn_sec_five_list', models.ManyToManyField(related_name='prf_trn_sec_five_list', to='subone.managementtrnsecfivelist')),
            ],
        ),
        migrations.AddField(
            model_name='professionaltrnsubpage',
            name='prf_trn_sec_seven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prf_trn_sec_seven', to='subone.professionaltrnsecseven'),
        ),
        migrations.AddField(
            model_name='professionaltrnsecseven',
            name='prf_trn_sec_seven_list',
            field=models.ManyToManyField(related_name='prf_trn_sec_seven_list', to='subone.professionaltrnsecsevenlist'),
        ),
    ]
