# Generated by Django 5.0.6 on 2024-09-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0029_professionaltrnsecseven_professionaltrnsecsevenlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaltrnsecfive',
            name='prf_trn_sec_five_list',
            field=models.ManyToManyField(related_name='prf_trn_sec_five_category', to='subone.professionaltrnsecfivecategory'),
        ),
        migrations.AlterField(
            model_name='professionaltrnsecfivecategory',
            name='prf_trn_sec_five_list',
            field=models.ManyToManyField(related_name='prf_trn_sec_five_list', to='subone.professionaltrnsecfivelist'),
        ),
    ]
