# Generated by Django 5.0.6 on 2024-09-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0030_alter_professionaltrnsecfive_prf_trn_sec_five_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionaltrnsecfive',
            old_name='prf_trn_sec_five_list',
            new_name='prf_trn_sec_five_category',
        ),
    ]
