# Generated by Django 5.0.6 on 2024-09-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0032_auditmetatag_auditsecfivelist_auditsecfourlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditsecone',
            old_name='audit_sec_two_list',
            new_name='audit_sec_one_list',
        ),
    ]
