# Generated by Django 5.0.6 on 2024-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0033_rename_audit_sec_two_list_auditsecone_audit_sec_one_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsecfive',
            name='list_tile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditsecfive',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditsecfour',
            name='list_tile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditsecfour',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditsecthree',
            name='list_tile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditsecthree',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
