# Generated by Django 5.0.6 on 2024-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0034_auditsecfive_list_tile_auditsecfive_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditsecsix',
            name='desc',
        ),
        migrations.AddField(
            model_name='auditsecsix',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
