# Generated by Django 5.0.6 on 2024-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0035_remove_auditsecsix_desc_auditsecsix_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaltrnsecfivecategory',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaltrnsecfivecategory',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
