# Generated by Django 5.0.6 on 2024-09-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0036_professionaltrnsecfivecategory_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaltrnsecfivecategory',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='professionaltrnsecfivecategory',
            name='section_title',
        ),
        migrations.AddField(
            model_name='professionaltrnsecfive',
            name='level_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professionaltrnsecfive',
            name='sub_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
