# Generated by Django 5.0.6 on 2024-09-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0037_remove_professionaltrnsecfivecategory_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StcMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('googlebot', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('google_site_verification', models.CharField(max_length=255)),
                ('og_url', models.CharField(max_length=255)),
                ('og_type', models.CharField(max_length=50)),
                ('og_title', models.CharField(max_length=255)),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='images/')),
                ('twitter_card', models.CharField(max_length=50)),
                ('twitter_domain', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('twitter_title', models.CharField(max_length=255)),
                ('twitter_description', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecEightList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StcSecFiveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StcSecFourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StcSecOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StcSecSevenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StcSecSixList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StcSecThreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StcSecTwoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.TextField()),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StcSecEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('paragraph_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stc_sec_eight_list', models.ManyToManyField(related_name='stc_sec_eight_list', to='subone.stcseceightlist')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('stc_sec_five_list', models.ManyToManyField(related_name='stc_sec_five_list', to='subone.stcsecfivelist')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('stc_sec_four_list', models.ManyToManyField(related_name='stc_sec_four_list', to='subone.stcsecfourlist')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('stc_sec_seven_list', models.ManyToManyField(related_name='stc_sec_seven_list', to='subone.stcsecsevenlist')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('stc_sec_six_list', models.ManyToManyField(related_name='stc_sec_six_list', to='subone.stcsecsixlist')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('stc_sec_three_list', models.ManyToManyField(related_name='stc_sec_three_list', to='subone.stcsecthreelist')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stc_sec_two_list', models.ManyToManyField(related_name='stc_sec_two_list', to='subone.stcsectwolist')),
            ],
        ),
        migrations.CreateModel(
            name='StcSubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lp_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('url_string', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('stc_meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_meta', to='subone.stcmetatag')),
                ('stc_sec_eight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_eight', to='subone.stcseceight')),
                ('stc_sec_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_five', to='subone.stcsecfive')),
                ('stc_sec_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_four', to='subone.stcsecfour')),
                ('stc_sec_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_one', to='subone.stcsecone')),
                ('stc_sec_seven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_seven', to='subone.stcsecseven')),
                ('stc_sec_six', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_six', to='subone.stcsecsix')),
                ('stc_sec_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_three', to='subone.stcsecthree')),
                ('stc_sec_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_two', to='subone.stcsectwo')),
            ],
        ),
    ]
