# Generated by Django 5.0.6 on 2024-09-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0038_stcmetatag_stcseceightlist_stcsecfivelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcsubpage',
            name='grc_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grc_meta', to='subone.grcmetatag'),
        ),
    ]
