# Generated by Django 5.0.6 on 2024-09-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0039_alter_grcsubpage_grc_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrcMainMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('googlebot', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('google_site_verification', models.CharField(max_length=255)),
                ('og_url', models.CharField(max_length=255)),
                ('og_type', models.CharField(max_length=50)),
                ('og_title', models.CharField(max_length=255)),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='images/')),
                ('twitter_card', models.CharField(max_length=50)),
                ('twitter_domain', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('twitter_title', models.CharField(max_length=255)),
                ('twitter_description', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecFiveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('desc', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecFourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('list_sub_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecThreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.TextField()),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecTwoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.TextField()),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('grcmain_sec_five_list', models.ManyToManyField(related_name='grcmain_sec_five_list', to='subone.grcmainsecfivelist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('list_title', models.TextField()),
                ('grcmain_sec_four_list', models.ManyToManyField(related_name='grcmain_sec_four_list', to='subone.grcmainsecfourlist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainSecThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grcmain_sec_three_list', models.ManyToManyField(related_name='grcmain_sec_three_list', to='subone.grcmainsecthreelist')),
            ],
        ),
        migrations.CreateModel(
            name='GrcMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lp_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('url_string', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('grcmain_meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grcmain_meta', to='subone.grcmainmetatag')),
                ('grcmain_sec_five', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grcmain_sec_five', to='subone.grcmainsecfive')),
                ('grcmain_sec_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grcmain_sec_four', to='subone.grcmainsecfour')),
                ('grcmain_sec_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grcmain_sec_one', to='subone.grcmainsecone')),
                ('grcmain_sec_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grcmain_sec_three', to='subone.grcmainsecthree')),
                ('grcmain_sec_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grcmain_sec_two', to='subone.grcmainsectwo')),
            ],
        ),
        migrations.AddField(
            model_name='grcmainsectwo',
            name='grcmain_sec_two_list',
            field=models.ManyToManyField(related_name='grcmain_sec_two_list', to='subone.grcmainsectwolist'),
        ),
    ]
