# Generated by Django 5.0.6 on 2024-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0040_grcmainmetatag_grcmainsecfivelist_grcmainsecfourlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcmainsecone',
            name='subDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grcmainsecone',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
