# Generated by Django 5.0.6 on 2024-09-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0041_grcmainsecone_subdesc_alter_grcmainsecone_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grcmainsecfour',
            name='grcmain_sec_four_list',
        ),
        migrations.RemoveField(
            model_name='grcmainsecfour',
            name='list_title',
        ),
        migrations.RemoveField(
            model_name='grcmainsecfourlist',
            name='list_sub_text',
        ),
        migrations.RemoveField(
            model_name='grcmainsecfourlist',
            name='list_text',
        ),
        migrations.AddField(
            model_name='grcmainsecfour',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grcmainsecfour',
            name='paragraph_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grcmainsecfourlist',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grcmainsecfourlist',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grcmainsecfour',
            name='section_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GrcMainSecFourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('grcmain_sec_four_list', models.ManyToManyField(related_name='grcmain_sec_four_list', to='subone.grcmainsecfourlist')),
            ],
        ),
        migrations.AddField(
            model_name='grcmainsecfour',
            name='grcmain_sec_four_category',
            field=models.ManyToManyField(related_name='grcmain_sec_four_category', to='subone.grcmainsecfourcategory'),
        ),
    ]
