# Generated by Django 5.0.6 on 2024-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0043_auditmainmetatag_auditmainsecone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditmainsecthree',
            name='auditmain_sec_five_list',
        ),
        migrations.AddField(
            model_name='auditmainsecthree',
            name='auditmain_sec_three_list',
            field=models.ManyToManyField(related_name='auditmain_sec_three_list', to='subone.auditmainsecthreelist'),
        ),
    ]
