# Generated by Django 5.0.6 on 2024-09-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0045_trnmainmetatag_trnmainsecfourlist_trnmainsecone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('location_map', models.TextField()),
            ],
        ),
    ]
