# Generated by Django 5.0.6 on 2024-09-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0048_remove_mstmainsecsixlist_img_mstmainsecsix_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstmainpage',
            name='mstmain_sec_seven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mstmain_sec_seven', to='subone.mstmainsecseven'),
        ),
        migrations.AlterField(
            model_name='mstmainsecseven',
            name='mstmain_sec_five_list',
            field=models.ManyToManyField(related_name='mstmain_sec_seven_list', to='subone.mstmainsecsevenlist'),
        ),
    ]
