# Generated by Django 5.0.6 on 2024-09-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0049_alter_mstmainpage_mstmain_sec_seven_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mstmainsecseven',
            old_name='mstmain_sec_five_list',
            new_name='mstmain_sec_seven_list',
        ),
    ]
