# Generated by Django 5.0.6 on 2024-09-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0050_rename_mstmain_sec_five_list_mstmainsecseven_mstmain_sec_seven_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtrnMainMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('googlebot', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('google_site_verification', models.CharField(max_length=255)),
                ('og_url', models.CharField(max_length=255)),
                ('og_type', models.CharField(max_length=50)),
                ('og_title', models.CharField(max_length=255)),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='images/')),
                ('twitter_card', models.CharField(max_length=50)),
                ('twitter_domain', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('twitter_title', models.CharField(max_length=255)),
                ('twitter_description', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PtrnMainSecFourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('desc', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PtrnMainSecOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('section_sub_title', models.TextField()),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PtrnMainSecThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PtrnMainSecTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PtrnMainSecTwoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.TextField()),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PtrnMainSecFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('ptrnmain_sec_four_list', models.ManyToManyField(related_name='ptrnmain_sec_four_list', to='subone.ptrnmainsecfourlist')),
            ],
        ),
        migrations.CreateModel(
            name='PtrnMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lp_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('url_string', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('ptrnmain_sec_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptrnmain_sec_four', to='subone.ptrnmainsecfour')),
                ('ptrnmain_sec_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptrnmain_sec_one', to='subone.ptrnmainsecone')),
                ('ptrnmain_sec_three', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptrnmain_sec_three', to='subone.ptrnmainsecthree')),
                ('ptrnmain_sec_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptrnmain_sec_two', to='subone.ptrnmainsectwo')),
            ],
        ),
        migrations.AddField(
            model_name='ptrnmainsectwo',
            name='ptrnmain_sec_two_list',
            field=models.ManyToManyField(related_name='ptrnmain_sec_two_list', to='subone.ptrnmainsectwolist'),
        ),
    ]
