# Generated by Django 5.0.6 on 2024-09-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0051_ptrnmainmetatag_ptrnmainsecfourlist_ptrnmainsecone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptrnmainpage',
            name='ptrnmain_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptrnmain_meta', to='subone.ptrnmainmetatag'),
        ),
    ]
