# Generated by Django 5.0.6 on 2024-09-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0053_stcmainmetatag_stcmainsecfivelist_stcmainsecfourlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stcmainsecfour',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
