# Generated by Django 5.0.6 on 2024-09-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0057_careerform_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='StcSecNine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='StcSecNineList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.TextField()),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='grcsecone',
            name='paragraph_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grcsecseven',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grcsectwo',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mstmainsecthree',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stcsecseven',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stcsubpage',
            name='stc_sec_nine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stc_sec_nine', to='subone.stcsecnine'),
        ),
        migrations.AddField(
            model_name='stcsecnine',
            name='stc_sec_nine_list',
            field=models.ManyToManyField(related_name='stc_sec_nine_list', to='subone.stcsecninelist'),
        ),
    ]
