# Generated by Django 5.0.6 on 2024-09-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0058_stcsecnine_stcsecninelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtrnMainSecThreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.TextField()),
                ('list_text', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ptrnmainsecthree',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='ptrnmainsecthree',
            name='img',
        ),
        migrations.AlterField(
            model_name='stcsecninelist',
            name='list_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stcsecninelist',
            name='list_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stcsecone',
            name='desc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptrnmainsecthree',
            name='ptrnmain_sec_three_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptrnmain_sec_three_list', to='subone.ptrnmainsecthreelist'),
        ),
    ]
