# Generated by Django 5.0.6 on 2024-09-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0059_ptrnmainsecthreelist_remove_ptrnmainsecthree_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptrnmainsecthree',
            name='ptrnmain_sec_three_list',
        ),
        migrations.AlterField(
            model_name='ptrnmainsecthreelist',
            name='list_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptrnmainsecthree',
            name='ptrnmain_sec_three_list',
            field=models.ManyToManyField(related_name='ptrnmain_sec_three_list', to='subone.ptrnmainsecthreelist'),
        ),
    ]
