# Generated by Django 5.0.6 on 2024-09-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0061_careerpagemetatag_careerpagesecone_careerpagesectwo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
