# Generated by Django 5.0.6 on 2024-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0063_blogctg_blogmetatag_blogsecfourlist_blogseconelist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsecfour',
            name='img',
        ),
        migrations.AddField(
            model_name='blogsecfour',
            name='pragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogsecone',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogsecfour',
            name='blog_sec_four_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_sec_four_list', to='subone.blogsecfourlist'),
        ),
        migrations.AlterField(
            model_name='blogsecfourlist',
            name='list_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsecfourlist',
            name='list_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsecone',
            name='section_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogseconelist',
            name='list_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsecthree',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsecthreelist',
            name='list_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogsectwo',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
