# Generated by Django 5.0.6 on 2024-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0064_remove_blogsecfour_img_blogsecfour_pragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='400-200.png', upload_to=''),
        ),
    ]
