# Generated by Django 5.0.6 on 2024-09-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0065_blog_date_alter_blog_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('audit_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('company_activities', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_auditor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_audit_team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_audit_team', models.TextField(blank=True, null=True)),
                ('feedback_for_intercert', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
