# Generated by Django 5.0.6 on 2024-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0066_customerfeedbackform'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
