# Generated by Django 5.0.6 on 2024-09-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0067_blog_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmgClientsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('author', models.TextField()),
                ('robots', models.TextField()),
                ('googlebot', models.TextField()),
                ('language', models.TextField()),
                ('google_site_verification', models.TextField()),
                ('og_url', models.TextField()),
                ('og_type', models.TextField()),
                ('og_title', models.TextField()),
                ('og_desc', models.TextField()),
                ('og_image', models.ImageField(upload_to='og_images/')),
                ('twitter_card', models.TextField()),
                ('twitter_domain', models.TextField()),
                ('twitter_url', models.TextField()),
                ('twitter_title', models.TextField()),
                ('twitter_desc', models.TextField()),
                ('twitter_image', models.ImageField(upload_to='twitter_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CmgSecFourList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.TextField()),
                ('products', models.TextField()),
                ('transportation', models.TextField()),
                ('advertisement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CmgSecOneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CmgSecThreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CmgSecTwoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='auditsectwolist',
            name='list_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grcsecthree',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CmgSecFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('cmg_sec_four_list', models.ManyToManyField(related_name='cmg_sec_four_list', to='subone.cmgsecfourlist')),
            ],
        ),
        migrations.CreateModel(
            name='CmgSecOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('cmg_sec_one_list', models.ManyToManyField(blank=True, null=True, related_name='cmg_sec_one_list', to='subone.cmgseconelist')),
            ],
        ),
        migrations.CreateModel(
            name='CmgSecThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('cmg_sec_three_list', models.ManyToManyField(related_name='cmg_sec_three_list', to='subone.cmgsecthreelist')),
            ],
        ),
        migrations.CreateModel(
            name='CmgSecTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('section_title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('cmg_sec_two_list', models.ManyToManyField(blank=True, null=True, related_name='cmg_sec_two_list', to='subone.cmgsectwolist')),
            ],
        ),
        migrations.CreateModel(
            name='CmgSubPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('lp_title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('url_string', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images/')),
                ('CmgMetaTags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmg_meta_tags', to='subone.cmgclientsmeta')),
                ('cmg_sec_four', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmg_sec_four', to='subone.cmgsecfour')),
                ('cmg_sec_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmg_sec_one', to='subone.cmgsecone')),
                ('cmg_sec_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmg_sec_three', to='subone.cmgsecthree')),
                ('cmg_sec_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmg_sec_two', to='subone.cmgsectwo')),
            ],
        ),
    ]
