# Generated by Django 5.0.6 on 2024-09-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0068_cmgclientsmeta_cmgsecfourlist_cmgseconelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('subtext', models.CharField(max_length=100)),
                ('nav_ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navs', to='subone.navctg')),
            ],
        ),
    ]
