# Generated by Django 5.0.6 on 2024-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0069_navctg_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='url_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
