# Generated by Django 5.0.6 on 2024-09-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0070_nav_url_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
