# Generated by Django 5.0.6 on 2024-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0071_alter_contactdetail_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
