# Generated by Django 5.0.6 on 2024-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0072_alter_contactdetail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navctg',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
