# Generated by Django 5.0.6 on 2024-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0073_navctg_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
