# Generated by Django 5.0.6 on 2024-09-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0074_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrcOfferingCtg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrcOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('subtext', models.CharField(blank=True, max_length=100, null=True)),
                ('url_string', models.CharField(blank=True, max_length=100, null=True)),
                ('grc_offering_ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_offering', to='subone.grcofferingctg')),
            ],
        ),
    ]
