# Generated by Django 5.0.6 on 2024-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0075_grcofferingctg_grcoffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcseceightlist',
            name='url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
