# Generated by Django 5.0.6 on 2024-09-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0076_alter_grcseceightlist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsecsevenlist',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
