# Generated by Django 5.0.6 on 2024-09-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0080_alter_stcseceightlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
