# Generated by Django 5.0.6 on 2024-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0081_certification_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryWeServeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='industryweserve',
            name='industry_lists',
            field=models.ManyToManyField(blank=True, null=True, related_name='industry_lists', to='subone.industryweservelist'),
        ),
    ]
