# Generated by Django 5.0.6 on 2024-09-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0083_rename_date_customerfeedbackform_assessment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('service', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
