# Generated by Django 5.0.6 on 2024-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0086_appealhandlingbanner_certificationguidlinebanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealhandlingbanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificationguidlinebanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificationprocessbanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificationverificationbanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complainthandlingprocessbanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedbackbanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grievancesbanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='suspendedclientbanner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
