# Generated by Django 5.0.6 on 2024-09-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0087_appealhandlingbanner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmgsectwolist',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cmgsectwo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cmgsectwolist',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmgsectwolist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
