# Generated by Django 5.0.6 on 2024-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0089_cmgsectwolistsectwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grcseconelist',
            name='paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grcseconelist',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
