# Generated by Django 5.0.6 on 2024-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0090_grcseconelist_paragraph_alter_grcseconelist_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnMainSecThreeListList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trnmainsecthreelist',
            name='list_text',
        ),
        migrations.AddField(
            model_name='trnmainsecthreelist',
            name='trnmain_sec_two_list_list',
            field=models.ManyToManyField(related_name='trnmain_sec_two_list_list', to='subone.trnmainsecthreelistlist'),
        ),
    ]
