# Generated by Django 5.0.6 on 2024-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0092_alter_professionaltrnsecfive_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcmainsecthree',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
