# Generated by Django 5.0.6 on 2024-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0093_alter_grcmainsecthree_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcsecone',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
