# Generated by Django 5.0.6 on 2024-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0094_alter_grcsecone_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grcsecone',
            name='grc_sec_one_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='grc_sec_one_list', to='subone.grcseconelist'),
        ),
    ]
