# Generated by Django 5.0.6 on 2024-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0095_alter_grcsecone_grc_sec_one_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trnmainsecthreelist',
            name='trnmain_sec_two_list_list',
        ),
        migrations.AddField(
            model_name='trnmainsecthreelist',
            name='trnmain_sec_three_list_list',
            field=models.ManyToManyField(related_name='trnmain_sec_three_list_list', to='subone.trnmainsecthreelistlist'),
        ),
    ]
