# Generated by Django 5.0.6 on 2024-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subone', '0096_remove_trnmainsecthreelist_trnmain_sec_two_list_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnmainsecthreelistlist',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trnmainsecthreelistlist',
            name='list_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
