from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('Test_api', views.Test_api, name='Test_api'),
    path('VideoBannerViewSet_api', views.VideoBannerViewSet_api, name='VideoBannerViewSet_api'),
    path('AboutContent_api', views.AboutContent_api, name='AboutContent_api'),
    path('Stat_api', views.Stat_api, name='Stat_api'),
    path('Client_api', views.Client_api, name='Client_api'),
    path('Client2_api', views.Client2_api, name='Client2_api'),
    path('Testimonial_api', views.Testimonial_api, name='Testimonial_api'),
    path('ServiceCarousel_api', views.ServiceCarousel_api, name='ServiceCarousel_api'),
    path('IndustryWeServe_api', views.IndustryWeServe_api, name='IndustryWeServe_api'),
    path('ApproachStep_api', views.ApproachStep_api, name='ApproachStep_api'),
    path('Certification_api', views.Certification_api, name='Certification_api'),
    path('AboutUsPage_api', views.AboutUsPage_api, name='AboutUsPage_api'),
    path('AboutUsMeta_api', views.AboutUsMeta_api, name='AboutUsMeta_api'),
    path('WhoWeAre_api', views.WhoWeAre_api, name='WhoWeAre_api'),
    path('OurMission_api', views.OurMission_api, name='OurMission_api'),
    path('WeAreGlobal_api', views.WeAreGlobal_api, name='WeAreGlobal_api'),
    path('WhyUs_api', views.WhyUs_api, name='WhyUs_api'),
    path('Accredition_api', views.Accredition_api, name='Accredition_api'),
    path('ImplementOfIP_api', views.ImplementOfIP_api, name='ImplementOfIP_api'),
    path('QualityPolicy_api', views.QualityPolicy_api, name='QualityPolicy_api'),
    path('ImpartialityPolicy_api', views.ImpartialityPolicy_api, name='ImpartialityPolicy_api'),
    path('SuspendedClients_api', views.SuspendedClients_api, name='SuspendedClients_api'),
    path('SuspendedClientsPage_api', views.SuspendedClientsPage_api, name='SuspendedClientsPage_api'),
    path('SuspendedClientsMeta_api', views.SuspendedClientsMeta_api, name='SuspendedClientsMeta_api'),
    path('AppealHandling_api', views.AppealHandling_api, name='AppealHandling_api'),
    path('AppealHandlingPage_api', views.AppealHandlingPage_api, name='AppealHandlingPage_api'),
    path('AHList_api', views.AHList_api, name='AHList_api'),
    path('ComplainHandlingMeta_api', views.ComplainHandlingMeta_api, name='ComplainHandlingMeta_api'),
    path('ComplainHandlingPageSerializer_api', views.ComplainHandlingPageSerializer_api, name='ComplainHandlingPageSerializer_api'),
    path('GrievancesPage_api', views.GrievancesPage_api, name='GrievancesPage_api'),
    path('GrievancesMeta_api', views.GrievancesMeta_api, name='GrievancesMeta_api'),
    path('GrievancesList_api', views.GrievancesList_api, name='GrievancesList_api'),
    path('CerificationProcessImg_api', views.CerificationProcessImg_api, name='CerificationProcessImg_api'),
    path('GrantorReuse_api', views.GrantorReuse_api, name='GrantorReuse_api'), 
    path('MaintainCertification_api', views.MaintainCertification_api, name='MaintainCertification_api'),
    path('DetailsForIssuing_api', views.DetailsForIssuing_api, name='DetailsForIssuing_api'),
    path('WithdrawOfCertification_api', views.WithdrawOfCertification_api, name='WithdrawOfCertification_api'),
    path('SuspensionOfCertification_api', views.SuspensionOfCertification_api, name='SuspensionOfCertification_api'),
    path('RestoringOfCertification_api', views.RestoringOfCertification_api, name='RestoringOfCertification_api'),
    path('ExpandingOrReducing_api', views.ExpandingOrReducing_api, name='ExpandingOrReducing_api'),
    path('CertificationProcessPage_api', views.CertificationProcessPage_api, name='CertificationProcessPage_api'),


#only url needed to access nested API
    path('GrcSubPage_api', views.GrcSubPage_api, name='GrcSubPage_api'),
    path('ManagementTrnSubPage_api', views.ManagementTrnSubPage_api, name='ManagementTrnSubPage_api'),
    path('ProfessionalTrnSubPage_api', views.ProfessionalTrnSubPage_api, name='ProfessionalTrnSubPage_api'),
    path('AuditSubPage_api', views.AuditSubPage_api, name='AuditSubPage_api'),
    path('StcSubPage_api', views.StcSubPage_api, name='StcSubPage_api'),
    path('GrcMainPage_api', views.GrcMainPage_api, name='GrcMainPage_api'),
    path('AuditMainPage_api', views.AuditMainPage_api, name='AuditMainPage_api'),
    path('TrnMainPage_api', views.TrnMainPage_api, name='TrnMainPage_api'),
    path('ContactDetail_api', views.ContactDetail_api, name='ContactDetail_api'),
    path('MstMainPage_api', views.MstMainPage_api, name='MstMainPage_api'),
    path('PtrnMainPage_api', views.PtrnMainPage_api, name='PtrnMainPage_api'),
    path('StcMainPage_api', views.StcMainPage_api, name='StcMainPage_api'),
    path('CareerForm_api', views.CareerForm_api, name='CareerForm_api'),
    path('ContactForm_api', views.ContactForm_api, name='ContactForm_api'),
    path('CareerPagePage_api', views.CareerPagePage_api, name='CareerPagePage_api'),
    path('PrivacyPolicyPage_api', views.PrivacyPolicyPage_api, name='PrivacyPolicyPage_api'),
    path('Blog_api', views.Blog_api, name='Blog_api'),
    path('BlogCatg_api', views.BlogCatg_api, name='BlogCatg_api'),
    path('Blog_api/<int:id>/', views.Blog_detail_api, name='Blog_detail_api'),
    path('CustomerFeedbackForm_api', views.CustomerFeedbackForm_api, name='CustomerFeedbackForm_api'),
 
]